== Dotfiles

Some of my dotfiles. Have a look at my https://blog.sebastian-daschner.com/entries/developer-productivity-masterclass-early-access[video course masterclass^] on developer productivity.

=== Structure

- All files and directories that start with a dot (`.`) belong to the user's home directory, directly or via symlink.
- `bin/` contains binaries and has to reside in the `$PATH`
- `examples/` contains examples for my videos and courses
- `uhk/` contains the configuration for my Ultimate Hacking Keyboard

=== IntelliJ Live templates

Copy the live templates into your IDEA configuration directory, under `<config-dir>/config/jba_config/templates/`.

NOTE: In IntelliJ `2020.1` the default configuration directory https://www.jetbrains.com/help/idea/tuning-the-ide.html#default-dirs[has changed^]. + 
For Linux, the default is now `~/.config/JetBrains/IntelliJIdea20XX.X/`

The `config/jba_config/templates.xml` files exists to avoid collisions with predefined default templates. You might have to merge in the parts of the XML file manually.
